# Generated by Django 6.0.5 on 2026-05-13 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsong',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='playlistsong',
            constraint=models.UniqueConstraint(fields=('playlist', 'song'), name='unique_song_in_playlist'),
        ),
    ]
