# Generated by Django 6.0.5 on 2026-05-12 06:15

from django.db import migrations, models
from django.utils.text import slugify

def gen_slugs(apps, schema_editor):
    Album = apps.get_model('backend', 'Album')
    for album in Album.objects.all():
        if not album.slug:
            base_slug = slugify(album.title)
            slug = base_slug
            counter = 1
            while Album.objects.filter(slug=slug).exclude(pk=album.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            album.slug = slug
            album.save(update_fields=['slug'])

    Artist = apps.get_model('backend', 'Artist')
    for artist in Artist.objects.all():
        if not artist.slug:
            base_slug = slugify(artist.name)
            slug = base_slug
            counter = 1
            while Artist.objects.filter(slug=slug).exclude(pk=artist.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            artist.slug = slug
            artist.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, unique=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, unique=False),
        ),
        migrations.RunPython(gen_slugs),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(unique=True, blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(unique=True, blank=True),
        ),

    ]
